version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/repo # directory where steps will run

    docker: # run the steps with Docker
      - image: circleci/openjdk:11-jdk
      
    steps:
      - checkout # check out source code to working directory
      - run: mvn install
      - store_artifacts: # store the uberjar as an artifact
          path: target/com.dexels.navajo.embedded.war-4.0.0-SNAPSHOT.war

