version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/repo # directory where steps will run

    docker: # run the steps with Docker
      - image: circleci/openjdk:11-jdk
      
    steps:
      - checkout # check out source code to working directory
      - run: mvn deploy -s .circleci/conf/settings.xml -T 1.5C deploy
      - store_artifacts: # store the uberjar as an artifact
          path: dexels-felix-war/target/com.dexels.embedded.war-3.0.0.war

